name: logbook_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  intl: ^0.17.0
  get_storage: ^2.0.3
  table_calendar: ^3.0.4
  flutter: 
    sdk: flutter
  flutter_slidable: ^1.2.0
  connectivity_plus: ^2.2.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

